name: parse_server
description: Parse Server Dart SDK.
version: 0.0.1
homepage: https://www.github.com/lotux
author: lotux <basirat@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  path: ^1.4.1
  web_socket_channel: ^1.0.6
  http: ^0.11.3

dev_dependencies:
  test: ^0.12.0
